import { cp, mkdir, rm, writeFile } from 'node:fs/promises';

const appName = 'numeria-studio';
const appVersion = '0.1.0';
const contractVersion = '0.1.0';
const timestamp = new Date().toISOString();

await rm('dist', { recursive: true, force: true });
await mkdir('dist/src', { recursive: true });
await mkdir('dist/contracts', { recursive: true });
await mkdir('dist/app/growth/start', { recursive: true });
await mkdir('dist/app/sessions/sample', { recursive: true });
await cp('index.html', 'dist/index.html');
await cp('index.html', 'dist/app/growth/start/index.html');
await cp('index.html', 'dist/app/sessions/sample/index.html');
await cp('src/main.js', 'dist/src/main.js');
await cp('src/reference-safety.js', 'dist/src/reference-safety.js');
await cp('src/contract-links.js', 'dist/src/contract-links.js');
await cp('src/styles.css', 'dist/src/styles.css');
await cp('contracts/status.json', 'dist/contracts/status.json');
await cp('contracts/status.json', 'dist/contracts/status');
await cp('contracts/production-flow-result.json', 'dist/contracts/production-flow-result.json');
await cp('contracts/production-flow-result.json', 'dist/contracts/production-flow-result');
await cp('contracts/data-boundaries.json', 'dist/contracts/data-boundaries.json');
await cp('contracts/data-boundaries.json', 'dist/contracts/data-boundaries');
await cp('contracts/operational-manifest.json', 'dist/contracts/operational-manifest.json');
await cp('contracts/operational-manifest.json', 'dist/contracts/operational-manifest');
await writeFile('dist/health', `${JSON.stringify({ appName, status: 'ok', timestamp }, null, 2)}\n`);
await writeFile('dist/version', `${JSON.stringify({ appName, appVersion, contractVersion, commitSha: 'optional', timestamp }, null, 2)}\n`);
console.log('Built static site into dist/');
